### ISSUE TITLE
Evolution fails to start

### ISSUE THREAD

**Issue by primeXchange** [getsolus/packages#2483]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

Evolution fails to start and presents a timeout to dataServer error:

![image](https://github.com/getsolus/packages/assets/40356316/ad35dd8e-7ed9-4b3a-ac2d-740dcafb2d41)

![image](https://github.com/getsolus/packages/assets/40356316/18521456-3990-4c83-8c63-fe7b8b709cd5)

```bash
Mai 06 17:09:39 t495 systemd[1346]: Starting evolution-source-registry.service - Evolution source registry...
░░ Subject: A start job for unit UNIT has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit UNIT has begun execution.
░░ 
░░ The job identifier is 671.
Mai 06 17:09:39 t495 evolution-sourc[4355]: cannot register existing type 'CamelM365Settings'
Mai 06 17:09:39 t495 evolution-sourc[4355]: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
Mai 06 17:09:39 t495 evolution-sourc[4355]: cannot add private field to invalid (non-instantiatable) type '<invalid>'
Mai 06 17:09:39 t495 evolution-sourc[4355]: g_once_init_leave: assertion 'result != 0' failed
Mai 06 17:10:09 t495 systemd[1346]: evolution-source-registry.service: start operation timed out. Terminating.
Mai 06 17:10:20 t495 systemd[1346]: evolution-source-registry.service: State 'stop-sigterm' timed out. Killing.
Mai 06 17:10:20 t495 systemd[1346]: evolution-source-registry.service: Killing process 4355 (evolution-sourc) with signal SIGKILL.
Mai 06 17:10:20 t495 systemd[1346]: evolution-source-registry.service: Main process exited, code=killed, status=9/KILL
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit UNIT has exited.
░░ 
░░ The process' exit code is 'killed' and its exit status is 9.
Mai 06 17:10:20 t495 systemd[1346]: evolution-source-registry.service: Failed with result 'timeout'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit UNIT has entered the 'failed' state with result 'timeout'.
Mai 06 17:10:20 t495 systemd[1346]: Failed to start evolution-source-registry.service - Evolution source registry.
░░ Subject: A start job for unit UNIT has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit UNIT has finished with a failure.
░░ 
░░ The job identifier is 671 and the job result is failed.
```

### Steps to reproduce

1. Boot into solus gnome 46 with kernel 6.8.8-288.current
2. Start evolution
3. The error comes up

### Expected result

Evolution should start

### Actual result

The error comes up

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

GNOME

### System details

```
System:
  Host: t495 Kernel: 6.8.8-288.current arch: x86_64 bits: 64
  Desktop: GNOME v: 46.1 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: LENOVO product: 20NJCTO1WW v: ThinkPad T495
    serial: <superuser required>
  Mobo: LENOVO model: 20NJCTO1WW serial: <superuser required> UEFI: LENOVO
    v: R12ET43W(1.13 ) date: 08/15/2019
Battery:
  ID-1: BAT0 charge: 43.5 Wh (100.0%) condition: 43.5/50.5 Wh (86.2%)
CPU:
  Info: quad core AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx [MT MCP]
    speed (MHz): avg: 1677 min/max: 1400/2300
Graphics:
  Device-1: AMD Picasso/Raven 2 [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel
  Device-2: Chicony ThinkPad T490 Webcam driver: uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 23.2.6 driver: X:
    loaded: amdgpu unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi
    gpu: amdgpu resolution: 1: 3440x1440 2: 1920x1080~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.0.6 renderer: AMD
    Radeon Vega 10 Graphics (radeonsi raven LLVM 16.0.6 DRM 3.57
    6.8.8-288.current)
Network:
  Device-1: Intel Wi-Fi 5 Wireless-AC 9x6x [Thunder Peak] driver: iwlwifi
  Device-2: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-3: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
Drives:
  Local Storage: total: 476.94 GiB used: 432.26 GiB (90.6%)
Info:
  Memory: total: 24 GiB note: est. available: 21.4 GiB used: 3.16 GiB (14.8%)
  Processes: 298 Uptime: 16m Shell: fish inxi: 3.3.34
```

### Other comments

It happened after sync week 17, and sync week 18 didn't fix the issue unfortunately.

**Comment by joebonrichie** [comment]
Could possibly be fixed by b0a07cd29543563d1085682ae06de705261f7b0a

**Comment by primeXchange** [comment]
Can I test this or will this be released with the next sync?

**Comment by davidjharder** [comment]
You can try installing `https://packages.getsol.us/unstable/e/evolution-ews/evolution-ews-3.52.1-54-1-x86_64.eopkg` but I think there was a `glibc` update before that, so the installation will fail. It will definitely be in the next sync

**Comment by malfisya** [comment]
Is this still a problem @primeXchange ?

**Comment by primeXchange** [comment]
Yes, this is still a problem.

`The job identifier is 2706.
Jun 21 09:43:32 t495 evolution-sourc[21897]: cannot register existing type 'CamelM365Settings'
Jun 21 09:43:32 t495 evolution-sourc[21897]: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
Jun 21 09:43:32 t495 evolution-sourc[21897]: cannot add private field to invalid (non-instantiatable) type '<invalid>'
Jun 21 09:43:32 t495 evolution-sourc[21897]: g_once_init_leave: assertion 'result != 0' failed
Jun 21 09:44:02 t495 systemd[1475]: evolution-source-registry.service: start operation timed out. Terminating.
Jun 21 09:44:13 t495 systemd[1475]: evolution-source-registry.service: State 'stop-sigterm' timed out. Killing.
Jun 21 09:44:13 t495 systemd[1475]: evolution-source-registry.service: Killing process 21897 (evolution-sourc) with signal SIGKILL.
Jun 21 09:44:13 t495 systemd[1475]: evolution-source-registry.service: Killing process 21903 (gdbus) with signal SIGKILL.
Jun 21 09:44:13 t495 systemd[1475]: evolution-source-registry.service: Main process exited, code=killed, status=9/KILL
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit UNIT has exited.
░░ 
░░ The process' exit code is 'killed' and its exit status is 9.
Jun 21 09:44:13 t495 systemd[1475]: evolution-source-registry.service: Failed with result 'timeout'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit UNIT has entered the 'failed' state with result 'timeout'.
Jun 21 09:44:13 t495 systemd[1475]: Failed to start evolution-source-registry.service - Evolution source registry.
░░ Subject: A start job for unit UNIT has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit UNIT has finished with a failure.
░░ 
░░ The job identifier is 2706 and the job result is failed.`
