### ISSUE TITLE
Plasma Apps not opening quickly -- possible apparmor related

### ISSUE THREAD

**Issue by pmaccarron** [getsolus/packages#3653]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

When I open windows or any dialogue box it takes a few minutes to open, for example if I open Kolourpaint and save as, the application freezes, this is the error in terminal:
```kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.NoReply"
"Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
```

If I open Gwenview, it appears on the taskbar but does not open. In terminal I get the following:
```QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setOpacity: Painter not active
QPainter::end: Painter not active, aborted
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.NoReply"
"Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
```
If I open Dolphin I get this error:
```kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.NoReply" 
 "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.NoReply" 
 "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
```

I tried to fix broken packages but it affect it, when I update I get the following error:
```[✗] Updating clr-boot-manager                                           failed

A copy of the command output follows:

[FATAL] cbm (../src/bootman/bootman.c:L562): FATAL: Cannot mount boot device /dev/nvme0n1p4 on /boot: No such device


 [✗] Updating clr-boot-manager                                           failed

A copy of the command output follows:

[FATAL] cbm (../src/bootman/bootman.c:L562): FATAL: Cannot mount boot device /dev/nvme0n1p4 on /boot: No such device


 [✓] Running depmod on kernel 6.9.12-297.current                        success
 [✓] Running depmod on kernel 6.6.43-251.lts                            success
 [✓] Updating systemd tmpfiles                                          success
 [✓] Reloading systemd configuration                                    success
 [✗] Compiling and Reloading AppArmor profiles                           failed

A copy of the command output follows:

Error: Could not replace profile /var/cache/apparmor/sbin.syslog-ng: Protocol error
Error: Could not replace profile /var/cache/apparmor/bin.ping: Protocol error
Error: Could not replace profile /var/cache/apparmor/sbin.klogd: Protocol error
Error: Could not replace profile /var/cache/apparmor/sbin.syslogd: Protocol error
failed to load AppArmor definitions, reason: exit status 71


 [✗] Compiling and Reloading AppArmor profiles                           failed

A copy of the command output follows:

Error: Could not replace profile /var/cache/apparmor/bin.ping: Protocol error
Error: Could not replace profile /var/cache/apparmor/sbin.klogd: Protocol error
Error: Could not replace profile /var/cache/apparmor/sbin.syslog-ng: Protocol error
Error: Could not replace profile /var/cache/apparmor/sbin.syslogd: Protocol error
failed to load AppArmor definitions, reason: exit status 71
```

### Steps to reproduce

1. Open Dolphin

### Expected result

Instant opening

### Actual result

Appears in taskbar, takes 2+ minutes to open

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Plasma

### System details

```System:
  Host: lenovo710s Kernel: 6.9.12-297.current arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 6.1.4 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: LENOVO product: 80W3 v: Lenovo ideapad 710S Plus-13IKB
    serial: <superuser required>
  Mobo: LENOVO model: LNVNB161216 v: SDK0J40709 WIN
    serial: <superuser required> UEFI: LENOVO v: 3NCN31WW(V2.53)
    date: 09/11/2017
Battery:
  ID-1: BAT1 charge: 34.7 Wh (100.0%) condition: 34.7/46.0 Wh (75.4%)
CPU:
  Info: dual core Intel Core i7-7500U [MT MCP] speed (MHz): avg: 802
    min/max: 400/2700
Graphics:
  Device-1: Intel HD Graphics 620 driver: i915 v: kernel
  Device-2: NVIDIA GM108M [GeForce 940MX] driver: nouveau v: kernel
  Device-3: Chicony EasyCamera driver: uvcvideo type: USB
  Display: wayland server: X.org v: 1.21.1.13 with: Xwayland v: 24.1.2
    compositor: kwin_wayland driver: X: loaded: modesetting,nouveau
    unloaded: fbdev,vesa dri: iris,nouveau gpu: i915,nouveau
    resolution: 1920x1080
  API: OpenGL v: 4.6 compat-v: 4.3 vendor: intel mesa v: 24.1.6
    renderer: Mesa Intel HD Graphics 620 (KBL GT2)
Network:
  Device-1: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter
    driver: ath10k_pci
Drives:
  Local Storage: total: 476.94 GiB used: 435.03 GiB (91.2%)
Info:
  Memory: total: 8 GiB note: est. available: 7.48 GiB used: 4.29 GiB (57.3%)
  Processes: 212 Uptime: 48m Shell: Bash inxi: 3.3.35
```

**Comment by pmaccarron** [comment]
This is still happening for me, searching more it seems to be related to udisks2, see https://github.com/storaged-project/udisks/issues/1139

**Comment by TraceyC77** [comment]
This is probably not related to that issue. The issue in udisks was fixed in 2.10.1, their latest release, which is what we have in the stable repo.
Also libblockdev in the repo is 3.2.0, which is the latest upstream release.

The errors about apparmor and cbm are more likely relevant

**Comment by TraceyC77** [comment]
The udisk errors are likely unrelated to this crash, but for completeness those are related to [this upstream bug](https://bugs.kde.org/show_bug.cgi?id=485194)

**Comment by TraceyC77** [comment]
@pmaccarron , Is this problem still happening for you on an up to date system?

**Comment by pmaccarron** [comment]
Hi @TraceyC77, the slowness to open those apps has stopped thankfully, I was still getting the AppArmor error on one machine recently but not my other. I intended to check last night but forgot, however, the main issue is resolved. Thanks!
